tunnel: 4a248b32-6ad9-461a-86fc-d7fbb0103d33
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: formexus.net
    path: /api/*
    service: http://backend:8080
  - hostname: www.formexus.net
    service: http://frontend:80
  - hostname: formexus.net
    service: http://frontend:80
  - service: http_status:404
