tunnel: 05bbafcd-9c95-49ba-873e-f2d111131a2e
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: formexus.net
    path: /api/*
    service: http://backend:8080
  - hostname: formexus.net
    service: http://frontend:80
  - hostname: www.formexus.net
    service: http://frontend:80
  - service: http_status:404
